# Generated by Django 6.0.1 on 2026-02-07 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('1', 'Short Form Brain Rot'), ('2', 'Long Form Brain Rot'), ('3', 'Upskill'), ('4', 'Friends & Family'), ('5', 'Hobbies'), ('6', 'Movies/Series'), ('others', 'Others')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poll_id', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.telegramuser')),
            ],
        ),
    ]
